//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pepe100.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public login()
        {
            this.tyontekijat21 = new HashSet<tyontekijat2>();
            this.tehtavia = new HashSet<tehtavia>();
        }
    
        public int LoginID { get; set; }
        public Nullable<int> YritysID { get; set; }
        public Nullable<int> HenkiloID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
    
        public virtual tyontekijat2 tyontekijat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tyontekijat2> tyontekijat21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tehtavia> tehtavia { get; set; }
        public virtual yritys yritys { get; set; }
    }
}
