//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pepe100.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pepeEntities : DbContext
    {
        public pepeEntities()
            : base("name=pepeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<loginyritys> loginyritys { get; set; }
        public virtual DbSet<tehtavia> tehtavia { get; set; }
        public virtual DbSet<tyontekijat2> tyontekijat2 { get; set; }
        public virtual DbSet<vastatarjoukset> vastatarjoukset { get; set; }
        public virtual DbSet<yritys> yritys { get; set; }
    }
}
