//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pepe100.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vastatarjoukset
    {
        public int VastaTarjousID { get; set; }
        public Nullable<int> TyoID { get; set; }
        public Nullable<int> YritysID { get; set; }
        public Nullable<int> HenkiloID { get; set; }
        public Nullable<int> TarjousHinta { get; set; }
        public Nullable<int> VastaTarjousHinta { get; set; }
        public Nullable<int> Prosentti { get; set; }
        public Nullable<int> ToteutunutHinta { get; set; }
    
        public virtual tehtavia tehtavia { get; set; }
        public virtual tyontekijat2 tyontekijat2 { get; set; }
        public virtual yritys yritys { get; set; }
    }
}
